# Lifesteal Mod configuration.

# If enabled, enchanted golden apples do not give you any effects.
allowGodApples: false

# If enabled, disables Strength II brewing and converts it to Strength I every time you try to apply it to yourself using commands.
allowStrengthII: false

# If enabled, limits enchantment levels to these for specific enchantments:
# Protection IV -> Protection III
# Fire Protection IV -> Fire Protection III
# Blast Protection IV -> Blast Protection III
# Projectile Protection IV -> Projectile Protection III
# Sharpness V -> Sharpness IV
# Power V -> Power IV
# Density V -> Density IV
enableEnchantmentLimits: false

# If enabled, allows netherite upgrades for diamond armor, sword, and axe.
allowNetheriteUpgrades: true

# If set to true, maces cannot be enchanted and have a 60-second attack cooldown (shown like ender pearls).
balancedMace = true

# Disables usage of ender pearls if enabled. Set to false be default
disableEnderPearls: true

# Makes crystals be unable to do any environment and player damage
disableCrystalDamage: true

# Enables cooldown for Riptide tridents
enableRiptideCooldown: false

# Maximum amount of hearts. Defaults to 20
maxHearts: 20

# Cooldown for Riptide enchantment
riptideCooldown: 200
