# Lifesteal singleplayer/client configuration.
# Gameplay options in this file are applied only to integrated singleplayer servers.

allowGodApples: false
allowStrengthII: false
enableEnchantmentLimits: false
allowNetheriteUpgrades: true
balancedMace: false
disableEnderPearls: false
disableEndCrystalDamage: true
enableRiptideCooldown: false
maxHearts: 20
riptideCooldown: 200
enableCustomDiscordRpc: true
